name: Deploy Landing Page

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.1.7

      - name: Install sshpass
        run: sudo apt-get install sshpass

      - name: Deploy to Server via SSH
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" | tr -d '\r' > key.pem
          chmod 600 key.pem
          ssh -o StrictHostKeyChecking=no -i key.pem -p 22 ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} 'sudo ./front-end.sh'


      - name: Send Telegram Notification on Success
        if: success()
        run: |
          curl -s --data "chat_id=${{ secrets.TELEGRAM_CHAT_ID }}" \
          --data-urlencode "text=<b>QuickMem Landing Page Deployed Successfully</b>
          <b>Repository</b>: ${{ github.repository }}
          <b>Committer</b>: ${{ github.actor }}
          <b>Commit Message</b>: ${{ github.event.head_commit.message }}
          <b>Branch</b>: ${{ github.ref_name }}
          <b>Changes</b>: <a href='https://github.com/pass-with-high-score/quickmem-landing-page/commit/${{ github.sha }}'>View Changes</a>
          <b>Action</b>: <a href='https://github.com/pass-with-high-score/quickmem-landing-page/actions/runs/${{ github.run_id }}'>View Action</a>
          <b>Link Landing page</b>: <a href='https://quickmem.app/'>https://quickmem.app/</a>" \
          --data "parse_mode=HTML" \
          https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage


      - name: Send Telegram Notification on Failure
        if: failure()
        run: |
          curl -s --data "chat_id=${{ secrets.TELEGRAM_CHAT_ID }}" \
          --data-urlencode "text=<b>QuickMem Landing Page Deployment Failed</b>
          <b>Repository</b>: ${{ github.repository }}
          <b>Committer</b>: ${{ github.actor }}
          <b>Commit Message</b>: ${{ github.event.head_commit.message }}
          <b>Branch</b>: ${{ github.ref_name }}
          <b>Changes</b>: <a href='https://github.com/pass-with-high-score/quickmem-landing-page/commit/${{ github.sha }}'>View Changes</a>
          <b>Action</b>: <a href='https://github.com/pass-with-high-score/quickmem-landing-page/actions/runs/${{ github.run_id }}'>View Action</a>" \
          --data "parse_mode=HTML" \
          https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage
