name: Deploy to Server

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.1.7

      - name: Set up Node.js
        uses: actions/setup-node@v4.0.3
        with:
          node-version: '20.x'

      - name: Install Dependencies
        run: npm install

      - name: Install sshpass
        run: sudo apt-get install sshpass

      - name: Deploy to Server via SSH with password
        run: |
          sshpass -p "${{ secrets.SERVER_PASSWORD }}" ssh -o StrictHostKeyChecking=no -p 22 ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} './deploy.sh'


      - name: Send Telegram Notification on Success
        if: success()
        run: |
          curl -s --data "chat_id=${{ secrets.TELEGRAM_CHAT_ID }}" \
          --data-urlencode "text=<b>QuickMem Server Deployed Successfully</b>
          <b>Repository</b>: ${{ github.repository }}
          <b>Committer</b>: ${{ github.actor }}
          <b>Commit Message</b>: ${{ github.event.head_commit.message }}
          <b>Branch</b>: ${{ github.ref_name }}
          <b>Changes</b>: <a href='https://github.com/pass-with-high-score/quickmem-server/commit/${{ github.sha }}'>View Changes</a>
          <b>Action</b>: <a href='https://github.com/pass-with-high-score/quickmem-server/actions/runs/${{ github.run_id }}'>View Action</a>
          <b>Link server</b>: <a href='https://api.nqmgaming.nl/'>https://api.nqmgaming.nl/</a>" \
          --data "parse_mode=HTML" \
          https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage


      - name: Send Telegram Notification on Failure
        if: failure()
        run: |
          curl -s --data "chat_id=${{ secrets.TELEGRAM_CHAT_ID }}" \
          --data-urlencode "text=<b>QuickMem Server Deployment Failed</b>
          <b>Repository</b>: ${{ github.repository }}
          <b>Committer</b>: ${{ github.actor }}
          <b>Commit Message</b>: ${{ github.event.head_commit.message }}
          <b>Branch</b>: ${{ github.ref_name }}
          <b>Changes</b>: <a href='https://github.com/pass-with-high-score/quickmem-server/commit/${{ github.sha }}'>View Changes</a>
          <b>Action</b>: <a href='https://github.com/pass-with-high-score/quickmem-server/actions/runs/${{ github.run_id }}'>View Action</a>" \
          --data "parse_mode=HTML" \
          https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage
